database:
    url: jdbc:mysql://localhost:3306/USER?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

spring:
    datasource:
        url: ${database.url}
        username: ${database.username}
        password: ${database.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        baseline-on-migrate: true
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

